"""
PrivIoT - Automated Defense & Quarantine Policy Generator (Production Grade)
Generates actual, ready-to-deploy network isolation rules, firewall configurations,
and DNS sinkhole policies for enterprise routers and firewalls.
Supported targets:
- Linux Gateway (iptables / nftables)
- pfSense / OPNsense Firewall
- Ubiquiti UniFi Dream Machine / EdgeRouter
- MikroTik RouterOS
- Pi-hole / AdGuard Home DNS Sinkhole
"""

import json
import logging
from typing import Dict, List, Any, Optional

logger = logging.getLogger(__name__)


class RemediationEngine:
    """
    Generates actionable remediation and network containment scripts.
    """

    def generate_iptables_rules(self, ip_address: str, mac_address: Optional[str] = None, allow_lan_gateway: str = "192.168.1.1") -> str:
        """
        Generate Linux iptables containment rules:
        - Blocks all WAN egress from IoT device
        - Prevents lateral traversal to other LAN workstations
        - Allows only required local gateway DHCP/DNS traffic
        """
        target_spec = f"-s {ip_address}"
        if mac_address and len(mac_address) == 17:
            mac_spec = f"-m mac --mac-source {mac_address}"
        else:
            mac_spec = ""

        rules = f"""# ==============================================================================
# PrivIoT Automated Quarantine Rules for {ip_address} ({mac_address or 'Unknown MAC'})
# Generated by PrivIoT Shield
# ==============================================================================

# 1. Flush any existing custom chain for this device
iptables -N PRIVIOT_ISOLATE_{ip_address.replace('.', '_')} 2>/dev/null || iptables -F PRIVIOT_ISOLATE_{ip_address.replace('.', '_')}

# 2. Allow local DHCP (UDP 67/68) and DNS to trusted gateway only
iptables -A PRIVIOT_ISOLATE_{ip_address.replace('.', '_')} {target_spec} {mac_spec} -d {allow_lan_gateway} -p udp --dport 53 -j ACCEPT
iptables -A PRIVIOT_ISOLATE_{ip_address.replace('.', '_')} {target_spec} {mac_spec} -d {allow_lan_gateway} -p udp --dport 67:68 -j ACCEPT

# 3. Block access to RFC1918 Private Internal LAN subnets (Lateral Movement Prevention)
iptables -A PRIVIOT_ISOLATE_{ip_address.replace('.', '_')} {target_spec} {mac_spec} -d 10.0.0.0/8 -j DROP
iptables -A PRIVIOT_ISOLATE_{ip_address.replace('.', '_')} {target_spec} {mac_spec} -d 172.16.0.0/12 -j DROP
iptables -A PRIVIOT_ISOLATE_{ip_address.replace('.', '_')} {target_spec} {mac_spec} -d 192.168.0.0/16 -j DROP

# 4. Drop direct unauthenticated outbound internet WAN forwarding
iptables -A PRIVIOT_ISOLATE_{ip_address.replace('.', '_')} {target_spec} {mac_spec} -o eth0 -j DROP

# 5. Insert containment chain at the top of the FORWARD table
iptables -I FORWARD 1 -j PRIVIOT_ISOLATE_{ip_address.replace('.', '_')}

# Logging quarantine enforcement
logger -t PrivIoT "Quarantine applied to IoT device {ip_address} [{mac_address}]"
"""
        return rules

    def generate_nftables_rules(self, ip_address: str, mac_address: Optional[str] = None) -> str:
        """Generate modern Linux nftables rule table."""
        return f"""# PrivIoT nftables Quarantine Policy for {ip_address}
table inet priviot_filter {{
    chain quarantine {{
        type filter hook forward priority -10; policy accept;
        
        # Block lateral movement to RFC1918 subnets
        ip saddr {ip_address} ip daddr {{ 10.0.0.0/8, 172.16.0.0/12, 192.168.0.0/16 }} drop
        
        # Block direct WAN outbound access
        ip saddr {ip_address} oifname "eth0" drop
    }}
}}
"""

    def generate_pfsense_rules(self, ip_address: str, device_name: str) -> str:
        """Generate pfSense / OPNsense XML / CLI rule block."""
        return f"""<!-- pfSense / OPNsense Firewall Rule Definition for PrivIoT Quarantine -->
<rule>
    <type>block</type>
    <interface>lan</interface>
    <ipprotocol>inet</ipprotocol>
    <descr>PrivIoT Quarantine - Block Lateral Traffic for {device_name} ({ip_address})</descr>
    <source>
        <address>{ip_address}</address>
    </source>
    <destination>
        <network>lan</network>
    </destination>
    <log>yes</log>
</rule>
<rule>
    <type>block</type>
    <interface>lan</interface>
    <ipprotocol>inet</ipprotocol>
    <descr>PrivIoT Quarantine - Block WAN Exfiltration for {device_name} ({ip_address})</descr>
    <source>
        <address>{ip_address}</address>
    </source>
    <destination>
        <any>1</any>
    </destination>
    <log>yes</log>
</rule>
"""

    def generate_unifi_cli_rules(self, ip_address: str, mac_address: Optional[str] = None) -> str:
        """Generate Ubiquiti UniFi Network CLI commands."""
        return f"""# Ubiquiti UniFi Isolation Configuration for {ip_address}
# Run on UniFi Gateway Console (UDM / USG)

# Create isolated firewall group
config.firewall.rule.isolate_{ip_address.replace('.', '_')}.action=DROP
config.firewall.rule.isolate_{ip_address.replace('.', '_')}.source.address={ip_address}
config.firewall.rule.isolate_{ip_address.replace('.', '_')}.destination.network=LAN_NETWORKS
config.firewall.rule.isolate_{ip_address.replace('.', '_')}.logging=true
"""

    def generate_mikrotik_script(self, ip_address: str, device_name: str) -> str:
        """Generate MikroTik RouterOS command block."""
        return f"""# MikroTik RouterOS Quarantine Script for {device_name}
/ip firewall filter
add chain=forward src-address={ip_address} dst-address-list=LAN_NETWORKS action=drop comment="PrivIoT Quarantine: Block Lateral LAN access for {device_name}"
add chain=forward src-address={ip_address} out-interface-list=WAN action=drop comment="PrivIoT Quarantine: Block WAN egress for {device_name}"
/log info "PrivIoT Quarantine applied to {ip_address}"
"""

    def generate_dns_sinkhole_blocklist(self, device_vendor: str) -> List[str]:
        """
        Generate telemetry & tracking domains to block in Pi-hole / AdGuard Home.
        """
        vendor_lower = (device_vendor or "").lower()
        blocklist = []

        if "tuya" in vendor_lower or "smart" in vendor_lower:
            blocklist.extend([
                "*.tuyaus.com",
                "*.tuyaeu.com",
                "*.tuya.com",
                "*.tuyacn.com",
                "mq.gw.tuyaeu.com"
            ])
        if "hikvision" in vendor_lower:
            blocklist.extend([
                "*.hik-connect.com",
                "dev.hik-connect.com",
                "*.ezvizlife.com"
            ])
        if "dahua" in vendor_lower:
            blocklist.extend([
                "*.dahuacloud.com",
                "*.easy4ip.com",
                "*.imoulife.com"
            ])
        if "tp-link" in vendor_lower or "tapo" in vendor_lower or "kasa" in vendor_lower:
            blocklist.extend([
                "*.tplinkcloud.com",
                "*.tplinkra.com",
                "aps1-security.tplinkcloud.com"
            ])
        if "wyze" in vendor_lower:
            blocklist.extend([
                "*.wyzecam.com",
                "*.wyze.com",
                "api.wyzecam.com"
            ])
        
        # Generic IoT telemetry sinks
        blocklist.extend([
            "iot-telemetry.unverified-broker.net",
            "device-metrics.iot-analytics-tracker.com"
        ])

        return blocklist


# Singleton instance
remediation_engine = RemediationEngine()
